
language: node_js

osx_image:
  - xcode8.1

node_js:
  - 7

before_script:
  - npm i @angular/cli -g --silent
  - npm i angular-cli-ghpages -g --silent

script:
  - npm run build:web
  - ngh --dir=dist/web --repo=https://$GH_TOKEN@github.com/bponomarenko/autoconfig-app.git --name="Borys Ponomarenko" --email=bponomarenko@gmail.com
  - npm run build:web4app
  - npm run build:app -- -p always

branches:
  only:
    - master
