language: node_js
node_js: 7

matrix:
  include:
    - os: osx
      env: TARGET_OS=osx
    - os: linux
      env: TARGET_OS=linux
    - os: osx
      osx_image: xcode8.1
      env: TARGET_OS=win

before_script: ./scripts/install.sh

script: ./scripts/build.sh

branches:
  only:
    - master
