language: node_js
node_js: 7

os:
  - osx
  - linux

before_script:
  - npm i @angular/cli -g --silent
  - npm i angular-cli-ghpages -g --silent

script: ./scripts/build.sh

branches:
  only:
    - master
